### ISSUE TITLE
error with binder 

### ISSUE THREAD

**Issue by alexgarciac** [genepattern/single_cell_clustering_notebook#17]
hi, I am trying to launch the binder but I get
Error loading genepattern/single_cell_clustering_notebook/master!
See logs below for details.

**Comment by alex-wenzel** [comment]
Thank you for letting us know. I also see an error when I try to run it in binder. We are currently refactoring some sections of the notebook and when those are done in the next couple weeks we will make sure the new version works on Binder as well.

**Comment by alex-wenzel** [comment]
Addressing this bug at #20

**Comment by alex-wenzel** [comment]
The latest version of the notebook now runs in Binder. Please let us know if there are any other issues.

**Comment by edjuaro** [comment]
Both @alex-wenzel and myself have tested the updated repo and the notebook runs with binder. Let us know if this works for you, @alexgarciac additionally, we are in the process of making this notebook available on notebook.genepattern.org
